import { Router } from 'express';
import { z } from 'zod';
import type { AuthedRequest } from '../middleware/auth';
import { requireRole } from '../middleware/auth';
import { prisma } from '../lib/db';
import { ApiError, asyncRoute } from '../lib/errors';
import { auditData } from '../lib/audit';
import { MockEcProvider, runEcSync } from '../services/ecSync';

export const adminRouter = Router(); adminRouter.use(requireRole('TD_ADMIN'));
adminRouter.get('/cycle', asyncRoute(async (_req, res) => res.json(await prisma.cycle.findFirst({ where: { status: 'ACTIVE' } }))));
adminRouter.put('/cycle', asyncRoute(async (req, res) => { const body = z.object({ label: z.string().min(1).max(30), startDate: z.coerce.date(), hireDateCutoff: z.coerce.date(), q1WindowStart: z.coerce.date(), q1WindowEnd: z.coerce.date(), midYearCutoff: z.coerce.date(), q2WindowStart: z.coerce.date(), q2WindowEnd: z.coerce.date(), yearEndCutoff: z.coerce.date(), status: z.enum(['DRAFT', 'ACTIVE', 'CLOSED']) }).parse(req.body); const auth = req as AuthedRequest; const saved = await prisma.$transaction(async (tx) => { if (body.status === 'ACTIVE') await tx.cycle.updateMany({ where: { status: 'ACTIVE', label: { not: body.label } }, data: { status: 'CLOSED' } }); const cycle = await tx.cycle.upsert({ where: { label: body.label }, create: body, update: body }); await tx.auditLog.create({ data: auditData({ actorEmployeeId: auth.employeeId, actorRole: 'TD_ADMIN', action: 'CYCLE_CONFIGURED', entityType: 'CYCLE', entityId: cycle.cycleId, ipAddress: req.ip }) }); return cycle; }); res.json(saved); }));
adminRouter.post('/cycle/reopen', asyncRoute(async (req, res) => { const { employeeId } = z.object({ employeeId: z.string().optional() }).parse(req.body); const auth = req as AuthedRequest; const cycle = await prisma.cycle.findFirst({ where: { status: { in: ['ACTIVE', 'CLOSED'] } }, orderBy: { startDate: 'desc' } }); if (!cycle) throw new ApiError(404, 'NOT_FOUND', 'Cycle not found'); await prisma.$transaction(async (tx) => { await tx.cycle.update({ where: { cycleId: cycle.cycleId }, data: { status: 'ACTIVE', isReopened: true } }); if (employeeId) await tx.sdp.updateMany({ where: { cycleId: cycle.cycleId, employeeId }, data: { status: 'DRAFT', sharingScope: null, submittedAt: null } }); await tx.auditLog.create({ data: auditData({ actorEmployeeId: auth.employeeId, actorRole: 'TD_ADMIN', action: 'CYCLE_REOPENED', entityType: employeeId ? 'SDP' : 'CYCLE', entityId: employeeId ?? cycle.cycleId, subjectEmployeeId: employeeId, ipAddress: req.ip }) }); }); res.status(204).end(); }));
adminRouter.get('/audit', asyncRoute(async (req, res) => { const page = z.coerce.number().int().min(1).default(1).parse(req.query.page); const pageSize = z.coerce.number().int().min(1).max(200).default(50).parse(req.query.pageSize); res.json(await prisma.auditLog.findMany({ orderBy: { createdAt: 'desc' }, skip: (page - 1) * pageSize, take: pageSize })); }));
adminRouter.get('/data-gaps', asyncRoute(async (_req, res) => res.json(await prisma.employee.findMany({ where: { isActive: true, syncGaps: { isEmpty: false } }, select: { employeeId: true, fullName: true, bu: true, syncGaps: true, lastSyncedAt: true } }))));
adminRouter.post('/ec-sync', asyncRoute(async (req, res) => res.status(202).json(await runEcSync(new MockEcProvider(), (req as AuthedRequest).employeeId, req.ip))));
adminRouter.get('/templates', asyncRoute(async (_req, res) => res.json(await prisma.emailTemplate.findMany({ orderBy: { key: 'asc' } }))));
adminRouter.put('/templates/:key', asyncRoute(async (req, res) => { const body = z.object({ subject: z.string().min(1).max(300), bodyHtml: z.string().min(1).max(50000) }).parse(req.body); const existing = await prisma.emailTemplate.findFirst({ where: { key: req.params.key, scope: 'TD_ADMIN', buId: null } }); res.json(existing ? await prisma.emailTemplate.update({ where: { templateId: existing.templateId }, data: { ...body, updatedBy: (req as AuthedRequest).employeeId } }) : await prisma.emailTemplate.create({ data: { key: req.params.key, scope: 'TD_ADMIN', ...body, updatedBy: (req as AuthedRequest).employeeId } })); }));
