import { PrismaClient, type SdpStatus } from '@prisma/client';
const prisma = new PrismaClient();

const bus = ['Operations', 'R&D', 'Corporate'];
const departments = ['Manufacturing', 'Quality', 'Engineering', 'Supply Chain', 'Finance'];
const statuses: SdpStatus[] = ['NOT_STARTED', 'DRAFT', 'SUBMITTED', 'CONVERSATION_CONFIRMED', 'IN_PROGRESS', 'CLOSED'];
const date = (value: string) => new Date(`${value}T00:00:00.000Z`);

async function main() {
  await prisma.cycle.upsert({ where: { label: '2026-27' }, update: { status: 'ACTIVE' }, create: { label: '2026-27', startDate: date('2026-04-01'), hireDateCutoff: date('2026-03-31'), q1WindowStart: date('2026-06-01'), q1WindowEnd: date('2026-06-30'), midYearCutoff: date('2026-09-30'), q2WindowStart: date('2026-12-01'), q2WindowEnd: date('2026-12-31'), yearEndCutoff: date('2027-03-15'), status: 'ACTIVE' } });
  for (let i = 1; i <= 2; i++) await prisma.employee.upsert({ where: { employeeId: `HR${i.toString().padStart(3, '0')}` }, update: {}, create: { employeeId: `HR${i.toString().padStart(3, '0')}`, fullName: `BUHR Partner ${i}`, email: `buhr${i}@bajajauto.co.in`, bu: bus[i - 1], function: 'Human Resources', department: 'Talent Development', designation: 'HR Business Partner', hireDate: date('2018-01-01') } });
  await prisma.employee.upsert({ where: { employeeId: 'ADMIN001' }, update: {}, create: { employeeId: 'ADMIN001', fullName: 'TD Administrator', email: 'td.admin@bajajauto.co.in', bu: 'Corporate', function: 'Human Resources', department: 'Talent Development', designation: 'TD Administrator', hireDate: date('2017-01-01') } });
  await prisma.roleGrant.upsert({ where: { employeeId_role: { employeeId: 'ADMIN001', role: 'TD_ADMIN' } }, update: {}, create: { employeeId: 'ADMIN001', role: 'TD_ADMIN' } });
  for (let i = 1; i <= 20; i++) { const bu = bus[(i - 1) % bus.length]; await prisma.employee.upsert({ where: { employeeId: `M${i.toString().padStart(3, '0')}` }, update: {}, create: { employeeId: `M${i.toString().padStart(3, '0')}`, fullName: `Manager ${i}`, email: `manager${i}@bajajauto.co.in`, buhrEmployeeId: bu === 'Corporate' ? 'HR002' : `HR${(((i - 1) % 2) + 1).toString().padStart(3, '0')}`, bu, function: departments[i % departments.length], department: departments[i % departments.length], designation: 'Department Manager', hireDate: date('2016-01-01') } }); }
  for (let i = 1; i <= 200; i++) { const bu = bus[(i - 1) % bus.length]; const managerId = `M${(((i - 1) % 20) + 1).toString().padStart(3, '0')}`; const buhrId = bu === 'Corporate' ? 'HR002' : `HR${(((i - 1) % 2) + 1).toString().padStart(3, '0')}`; await prisma.employee.upsert({ where: { employeeId: `E${i.toString().padStart(4, '0')}` }, update: {}, create: { employeeId: `E${i.toString().padStart(4, '0')}`, fullName: `Employee ${i}`, email: `employee${i}@bajajauto.co.in`, managerEmployeeId: managerId, managerEmail: `manager${((i - 1) % 20) + 1}@bajajauto.co.in`, buhrEmployeeId: buhrId, buhrEmail: `${buhrId.toLowerCase()}@bajajauto.co.in`, bu, function: departments[i % departments.length], department: departments[i % departments.length], designation: i % 3 ? 'Senior Engineer' : 'Team Lead', hireDate: date(`20${18 + (i % 7)}-01-01`) } }); }
  const cycle = await prisma.cycle.findUniqueOrThrow({ where: { label: '2026-27' } });
  for (let i = 1; i <= 36; i++) { const employeeId = `E${i.toString().padStart(4, '0')}`; const status = statuses[i % statuses.length]; const submitted = !['NOT_STARTED', 'DRAFT'].includes(status); await prisma.sdp.upsert({ where: { employeeId_cycleId: { employeeId, cycleId: cycle.cycleId } }, update: {}, create: { employeeId, cycleId: cycle.cycleId, status, sharingScope: submitted ? (i % 2 ? 'FULL' : 'GOALS_ONLY') : null, submittedAt: submitted ? new Date() : null, conversationConfirmedAt: ['CONVERSATION_CONFIRMED', 'IN_PROGRESS', 'CLOSED'].includes(status) ? new Date() : null, managerEmployeeIdSnapshot: `M${(((i - 1) % 20) + 1).toString().padStart(3, '0')}`, reflection: { create: { q1Words: ['Curious', 'Reliable', 'Collaborative'], q2Text: 'I bring a calm and structured approach to complex operational challenges and help the team make clear decisions.', q3Text: 'My strengths are root cause analysis, cross functional collaboration, and building practical systems that teams adopt.', q4Text: 'I led a difficult improvement project and delivered measurable results while supporting colleagues through the change.', q5Text: 'I need to delegate earlier, invite challenge more openly, and communicate risks before I have complete information.', q6Text: 'I want to become a trusted leader who develops strong teams and improves performance across the wider organisation.' } }, goals: { create: { sortOrder: 1, title: 'Strengthen cross functional leadership', domain: 'LEADERSHIP', whyItMatters: 'Better coordination will improve delivery and reduce delays.', grownWhen: 'Teams resolve dependencies early and deliver shared outcomes consistently.', actionDo: 'Lead a monthly cross functional review.', actionLearn: 'Complete the internal leadership programme.', actionConnect: 'Seek monthly coaching from a senior leader.', supportNeeded: 'Protected time and sponsorship from my manager.' } } } }); }
  for (const template of ['NUDGE_SDP_SUBMISSION', 'AUTO_SDP_SUBMITTED', 'AUTO_FEEDBACK_SHARED']) {
    const existing = await prisma.emailTemplate.findFirst({ where: { key: template, scope: 'SYSTEM_DEFAULT', buId: null } });
    if (!existing) await prisma.emailTemplate.create({ data: { key: template, scope: 'SYSTEM_DEFAULT', subject: 'SDP update', bodyHtml: '<p>You have an SDP action or update.</p>' } });
  }
}

main().finally(() => prisma.$disconnect());
